version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: tournament_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: tsdb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/001_init_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: tournament_system
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: postgres://postgres:123123@db:5432/tsdb?sslmode=disable
      JWT_SECRET_KEY: YERNUR
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local